
- name: Debian - Add Beats repository key
  apt_key: url="http://packages.elasticsearch.org/GPG-KEY-elasticsearch" state=present
  when: use_repository

- name: Debian - add beats repository
  apt_repository: repo="deb http://packages.elastic.co/beats/apt stable main" state=present
  when: use_repository

- name: Debian - Ensure {{beat}} is installed
  apt: name={{beat}}{% if beats_version is defined and beats_version != "" %}={{ beats_version }}{% endif %} state=present cache_valid_time=86400
  when: use_repository
  register: beat_install
  notify: restart beat

- name: Debian - Download {{beat}} from url
  get_url: url={% if beats_custom_package_url is defined %}{{ beats_custom_package_url }}{% else %}{{ beats_package_url }}/{{beat}}/{{beat}}_{{ beats_version }}_amd64.deb{% endif %} dest=/tmp/{{beat}}_{{ beats_version }}_amd64.deb validate_certs=no
  register: beat_install
  when: not use_repository

- name: Debian - Ensure {{beat}} is installed from downloaded package
  apt: deb=/tmp/{{beat}}_{{ beats_version }}_amd64.deb
  when: not use_repository
  register: beat_install
  notify: restart beat